version: "3"
services:
  redis:
    image: redis:latest
    container_name: redis-db
    networks:
      - app-network

  api:
    build:
      context: ./react-flask-app/api
    container_name: flask-server-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_RUN_FROM_CLI=true
      - FLASK_APP=python-backend/api.py
    command: flask run --host=0.0.0.0 --port=5000
    networks:
      - app-network
    depends_on:
      - redis

  client:
    build:
      context: ./react-flask-app/client
      dockerfile: ./Dockerfile
    container_name: react-front-app
    environment:
      - DOCKER_ENV=true
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network: