version: "3"
services:
  redis:
    image: redis:latest
    container_name: redis-db
    networks:
      - app-network

  api:
    build:
      context: ./api
    container_name: flask-server-app
    ports:
      - "5000:5000"
    networks:
      - app-network
    depends_on:
      - redis

  client:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: react-front-app
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network: